config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root "application#welcome"
	resources :users, only: [:new, :create, :index, :show, :update, :edit] do
		resources :friends, only: [:index, :create, :update] #all friends
		resources :books, only: [:new, :create, :index, :show]
	end

	get 'users/:id/pending_friends', to: 'friends#pending_friends', as: 'pending'

	get "signin" => "sessions#new"
	resources :sessions, only: [:create, :destroy]
	get '/auth/facebook/callback' => 'sessions#create'


	resources :books, only: [:index, :show]

	resources :user_books, only: [:index, :edit]
	patch "user_books/:id" => "user_books#update", as: "editUserBook"
	post "addbook/:id" => "user_books#create", as: "addbook"

end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_books
	has_many :books, through: :user_books
	has_many :friendships
	# , :foreign_key => "user_id", :class_name => "Friendship"
	has_many :friends,  -> { Friendship.accepted }, :through => :friendships

	validates :username, uniqueness: { case_sensitive: false }
	validates :username, presence: true
	has_secure_password

	before_create :set_friend_id

	def friend_request=(user)
		if User.all.include?(user)
			Friendship.friend_request(self, user)
		end
	end

	def friend_requests
		Friendship.requests(self)
	end

	def pending_requests
		Friendship.pending_requests(self)
	end

	def accept_friend_request(user)

		if User.all.include?(user)
			Friendship.accept_request(user, self)
			user.save
			self.save
		end
	end

	private
	def set_friend_id
  		last_friend_id = User.maximum(:friend_id)
 		if !!last_friend_id
  			self.friend_id = last_friend_id + 1
  		else
  			self.friend_id = 1
  		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login
	skip_before_action :require_login, only: [:new, :create]


	def index
		@users = User.all

	end

	def new
		if logged_in?
			redirect_to user_path(current_user)
		else
			@user = User.new
		end
	end

	def create
		@user = User.new(user_params)

		if @user.save
			session[:user_id] = @user.id
			redirect_to user_path(@user)
		else
			flash[:alert]
			render :new
		end
	end

	def show
		@user = User.find_by(id: params[:id])
	end

	private
	def user_params
		params.require(:user).permit(:username, :password)
	end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/index.html.erb
<h1>User List</h1>

<ul>
	<% @users.each do |user| %>
		<li><%= link_to user.username, user_path(user) %>,
			<%= link_to "User Libray", user_books_path(user.id), class: "userBooks", user_id: user.id %>
		</li>

		<div><ul id="userbooks-<%= user.id %>"></ul></div>

	<% end %>	
</ul>	

app/views/users/new.html.erb
<h1>New User Form</h1>

<% if @user.errors.any? %>
	<div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited the creation of a new user:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
	<br>
<% end %>	

<%= form_for(@user) do |f| %>
	<%= f.label :username, "Username: " %>
	<%= f.text_field :username %><br>

	<%= f.label :password, "Password: " %>
	<%= f.password_field :password %><br>

	<%= f.submit "Create User" %>

<% end %>

app/views/users/show.html.erb
<h1 class="text-center"><%= @user.username %></h1>
<% if current_user != @user &&  all_friends_including_pending.exclude?(@user) %>
  <h4><%= link_to "Add Friend", user_friends_path(@user), method: "post" %></h4>

<% elsif pending_friend_requests.include?(@user) %>
  <h4><%= link_to "Accept Friend Request", user_friend_path(user_id: current_user, id: @user), method: "patch" %></h4>
<% end %>

<div class="row">
  <div class="col-md-6"><h3>Currently Reading </h3>
  <%= button_to "Add Book", new_user_book_path(current_user), id: "addBookForm", method: "get" if current_user == @user %>
  <br>
  <div id="userNewBook">
  
  </div>
  <br>
    <ul id= 'books'>
        <%= render partial: "books/index", collection: currently_reading, as: :book %>     
    </ul>
  </div>
  <div class="col-md-6"><h3>Finished Books</h3>
    <%= render partial: "books/index", collection: finished_books, as: :book %>
  </div>
</div>