config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root "application#welcome"
	resources :users, only: [:new, :create, :index, :show, :update, :edit] do
		resources :friends, only: [:index, :create, :update] #all friends
		resources :books, only: [:new, :create, :index, :show]
	end

	get 'users/:id/pending_friends', to: 'friends#pending_friends', as: 'pending'

	get "signin" => "sessions#new"
	resources :sessions, only: [:create, :destroy]
	get '/auth/facebook/callback' => 'sessions#create'


	resources :books, only: [:index, :show]

	resources :user_books, only: [:index, :edit]
	patch "user_books/:id" => "user_books#update", as: "editUserBook"
	post "addbook/:id" => "user_books#create", as: "addbook"

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :genre
	belongs_to :author
	has_many :user_books
	has_many :users, through: :user_books

	validates :title, uniqueness: { case_sensitive: false }
	validates :title, presence: true

	def author_attributes=(author_attributes)
	  	author_attributes.each do |i, attribute| 
	  		if !attribute.blank?
	  			author = Author.find_or_create_by(name: attribute)
				self.author = author 
			end	
		end
  	end

  	def genre_attributes=(genre_attributes)
  		genre_attributes.each do |i, attribute|
  			if !attribute.blank?
	  			genre = Genre.find_or_create_by(title: attribute)
				self.genre = genre 	
			end	
		end
  	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController 
	before_action :require_login
	skip_before_action :require_login, only: [:index]

	def index
		if params[:user_id]
			user = User.find(params[:user_id])
			@books = user.books
		else
			@books = Book.all
		end
		
		respond_to do |format|
	      format.html { render :index }
	      format.json { render json: @books}
    	end
		# @user_book = UserBook.new
	end

	def show 
	
		@book = Book.find_by(id: params[:id])
		@user_book = UserBook.find_by(book_id: @book.id, user_id: current_user.id)
		@user_book_ids = current_user.book_ids
		@all_books = Book.ids

		respond_to do |format|
	      format.html { render :show }
	      format.json { render json: @book}
		end
	end

	def new
		@book = Book.new
		render :layout => false
	end

  def create
    	@book = Book.new(book_params)
		if @book.save
			current_user.user_books.create(book_id: @book.id)
    		render json: @book, status: 201
		else
			render :new
	end
  end

private 
	def book_params
		if author_id? && genre_id?
			params.require(:book).permit(:title, :author_id, :genre_id)
		elsif author_id? && !genre_id?
			params.require(:book).permit(:title, :author_id, :genre_attributes => [:title])
		elsif !author_id? && genre_id?
			params.require(:book).permit(:title, :genre_id, :author_attributes => [:name])
		else
			params.require(:book).permit(:title, :genre_attributes => [:title], :author_attributes => [:name])
		end
	end

	def author_id?
		params[:book][:author_id] != ""
	end	

	def genre_id?
		params[:book][:genre_id] != ""
	end
end

app/views/books/_index.html.erb
<% if logged_in?%>
  
      <li><%= link_to book.title.titleize, book_path(book) %>, by: <%=book.author.name.titleize %></li>
 
<% else %>

      <li><%= book.title.titleize %>, by: <%=book.author.name.titleize %></li>
    
<% end %>

app/views/books/_show.html.erb
<h1 id="bookTitle"><%= book.title.titleize %></h1>
<h4 id="bookAuthor">By: <%= book.author.name.titleize %></h4>
<h4 id="bookGenre">Genre: <%= book.genre.title.titleize %></h4>

<% if !!current_book(book) %>
	<p>Currently Reading, on page: <%= current_book(book).page %></p>
<% end %>

app/views/books/index.html.erb
<h1>List of Books</h1>

<ul>
    <%= render partial: "index", collection: @books, as: :book %>

</ul>

app/views/books/new.html.erb
<%= form_for @book, url: user_books_path(current_user) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field-title">
    <%= f.label :title %><br>
    <%= f.text_field :title %><br><br>

  </div>


  <%= button_tag "Select Author", type: "button", class: "select-author" %> or <%= button_tag "Create New Author", type: "button", class: "new-author"%>


  <div class="field-author" style="display: none;">
    <strong>Author:</strong><br><br>

    <%= f.collection_radio_buttons :author_id, Author.all, :id, :name do |b| %>
      <%= b.radio_button %>

      <%= "#{b.text}" %>
    <% end %>
  </div> <br>


  <div class="field-newAuthor" style="display: none;">
    <strong>New Author: </strong><br>

    <%= f.fields_for :author_attributes do |author_form| %>
      <%= author_form.label :name %>
      <%= author_form.text_field :name %>
    <% end %>  
  </div><br>

  <%= button_tag "Select Genre", type: "button", class: "select-genre" %> or <%= button_tag "Create New Genre", type: "button", class: "new-genre"%>

  </div>

  <div class="field-genre" style="display: none;">
    <strong>Genre:</strong><br><br>

    <%= f.collection_radio_buttons :genre_id, Genre.all, :id, :title do |b| %>
      <%= b.radio_button %>

      <%= "#{b.text}" %>
    <% end %>
  </div> <br>


  <div class="field-newGenre" style="display: none;">
    <strong>New Genre: </strong><br>

    <%= f.fields_for :genre_attributes do |genre_form| %>
      <%= genre_form.label :title %>
      <%= genre_form.text_field :title %>
    <% end %>  
  </div> 


  <div class="actions"><br>
    <%= f.submit "Create Book", id: "submit-NewBook", uid: current_user.id %>
  </div>

<% end %>

app/views/books/show.html.erb
<%= render partial: 'show', locals: {book: @book} %>


<%= link_to("Add Book", addbook_path(@book), id: "originalAddBookLink" ,method: :post) if logged_in? && user_books.exclude?(@book) %>

<div id= "addBookLink" style="display: none;" >
</div>

<div id="bookmark-container" style="display: none;">
</div>

<% if logged_in? %>
	<div><%= link_to("Bookmarks", edit_user_book_path(@book), id: "bookmarks") if user_books.include?(@book) %></div>
	<div><%= link_to "Next", book_path(@book), class: "userBook", user_id: current_user.id, book_id: @book.id, user_book_ids: @user_book_ids, all_book_ids: @all_books %></div>
<% end %>