config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root "application#welcome"
	resources :users, only: [:new, :create, :index, :show, :update, :edit] do
		resources :friends, only: [:index, :create, :update] #all friends
		resources :books, only: [:new, :create, :index, :show]
	end

	get 'users/:id/pending_friends', to: 'friends#pending_friends', as: 'pending'

	get "signin" => "sessions#new"
	resources :sessions, only: [:create, :destroy]
	get '/auth/facebook/callback' => 'sessions#create'


	resources :books, only: [:index, :show]

	resources :user_books, only: [:index, :edit]
	patch "user_books/:id" => "user_books#update", as: "editUserBook"
	post "addbook/:id" => "user_books#create", as: "addbook"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClubRailsPortfolioProject</title>
    
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %> 
    <%= csrf_meta_tags %>

  </head>

  <body>

  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="/books">Books</a></li>
        <% if logged_in? %>
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Friends", user_friends_path(current_user) %></li>
            <li><%= link_to "Pendings Friends", pending_path(current_user) %></li>
            <li><%= link_to "Log Out", session_path(current_user), method: :delete %></li>
        <% end %>

        
        
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <%= yield %>
    <%= javascript_include_tag 'main'  %>
       <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>